import { getStrataPaths, type MessageRecord, SessionStore } from "@strata/core";
import type { ModelAdapter } from "./types.js";

// Prompts ported verbatim from pi-mono (`coding-agent/src/core/compaction/{utils,compaction}.ts`).

const SUMMARIZATION_SYSTEM_PROMPT = `You are a context summarization assistant. Your task is to read a conversation between a user and an AI coding assistant, then produce a structured summary following the exact format specified.

Do NOT continue the conversation. Do NOT respond to any questions in the conversation. ONLY output the structured summary.`;

const SUMMARIZATION_PROMPT = `The messages above are a conversation to summarize. Create a structured context checkpoint summary that another LLM will use to continue the work.

Use this EXACT format:

## Goal
[What is the user trying to accomplish? Can be multiple items if the session covers different tasks.]

## Constraints & Preferences
- [Any constraints, preferences, or requirements mentioned by user]
- [Or "(none)" if none were mentioned]

## Progress
### Done
- [x] [Completed tasks/changes]

### In Progress
- [ ] [Current work]

### Blocked
- [Issues preventing progress, if any]

## Key Decisions
- **[Decision]**: [Brief rationale]

## Next Steps
1. [Ordered list of what should happen next]

## Critical Context
- [Any data, examples, or references needed to continue]
- [Or "(none)" if not applicable]

Keep each section concise. Preserve exact file paths, function names, and error messages.`;

const UPDATE_SUMMARIZATION_PROMPT = `The messages above are NEW conversation messages to incorporate into the existing summary provided in <previous-summary> tags.

Update the existing structured summary with new information. RULES:
- PRESERVE all existing information from the previous summary
- ADD new progress, decisions, and context from the new messages
- UPDATE the Progress section: move items from "In Progress" to "Done" when completed
- UPDATE "Next Steps" based on what was accomplished
- PRESERVE exact file paths, function names, and error messages
- If something is no longer relevant, you may remove it

Use this EXACT format:

## Goal
[Preserve existing goals, add new ones if the task expanded]

## Constraints & Preferences
- [Preserve existing, add new ones discovered]

## Progress
### Done
- [x] [Include previously done items AND newly completed items]

### In Progress
- [ ] [Current work - update based on progress]

### Blocked
- [Current blockers - remove if resolved]

## Key Decisions
- **[Decision]**: [Brief rationale] (preserve all previous, add new)

## Next Steps
1. [Update based on current state]

## Critical Context
- [Preserve important context, add new if needed]

Keep each section concise. Preserve exact file paths, function names, and error messages.`;

const SUMMARY_MARKER = "Summary of our earlier conversation:\n\n";

export interface CompactSessionOptions {
  sessionId: string;
  model: ModelAdapter;
  repoRoot?: string;
  signal?: AbortSignal;
}

export interface CompactSessionResult {
  sessionId: string;
  summary: string;
  messagesSummarized: number;
  /** True if the session already had a summary and we merged new messages into it. */
  incremental: boolean;
}

/**
 * Replaces the session's message log with a single user-role summary message
 * generated by the model. Returns the summary so the caller can surface it.
 *
 * If the session already starts with a summary message (i.e. it has been
 * compacted before), the model receives the previous summary in
 * `<previous-summary>` tags plus the new messages in `<conversation>` tags
 * and is asked to UPDATE the summary. Pi calls this incremental compaction.
 *
 * On a continuation after compaction the agent loop sees:
 *   [fresh system prompt, fresh run-context, summary message, new user turn]
 */
export async function compactSession(
  options: CompactSessionOptions,
): Promise<CompactSessionResult> {
  const repoRoot = getStrataPaths(options.repoRoot).repoRoot;
  const store = await SessionStore.open(repoRoot);
  try {
    const allMessages = store
      .listMessages(options.sessionId)
      .filter((message) => message.role !== "system");
    if (allMessages.length === 0) {
      throw new Error("no messages to compact");
    }

    const detected = detectPreviousSummary(allMessages);
    const incremental = detected !== undefined && detected.newMessages.length > 0;
    if (detected !== undefined && detected.newMessages.length === 0) {
      throw new Error("nothing new to compact since the last compaction");
    }

    const messagesToSummarize = detected === undefined ? allMessages : detected.newMessages;
    const conversationText = messagesToSummarize
      .map((message) => `[${message.role}] ${message.content}`)
      .join("\n\n");

    let userPrompt: string;
    if (incremental && detected !== undefined) {
      userPrompt =
        `<conversation>\n${conversationText}\n</conversation>\n\n` +
        `<previous-summary>\n${detected.previous}\n</previous-summary>\n\n` +
        UPDATE_SUMMARIZATION_PROMPT;
    } else {
      userPrompt = `<conversation>\n${conversationText}\n</conversation>\n\n${SUMMARIZATION_PROMPT}`;
    }

    const request: Parameters<ModelAdapter["complete"]>[0] = {
      messages: [
        { role: "system", content: SUMMARIZATION_SYSTEM_PROMPT },
        { role: "user", content: userPrompt },
      ],
      tools: [],
    };
    if (options.signal !== undefined) {
      request.signal = options.signal;
    }
    const response = await options.model.complete(request);
    const summary = response.content.trim();
    if (summary === "") {
      throw new Error("model returned empty summary");
    }

    store.deleteMessages(options.sessionId);
    await store.appendMessage({
      sessionId: options.sessionId,
      role: "user",
      content: `${SUMMARY_MARKER}${summary}`,
    });
    await store.appendEvent(options.sessionId, "compaction.completed", {
      messagesSummarized: messagesToSummarize.length,
      incremental,
      summary,
    });

    return {
      sessionId: options.sessionId,
      summary,
      messagesSummarized: messagesToSummarize.length,
      incremental,
    };
  } finally {
    store.close();
  }
}

/**
 * Default ratio of (latest_context_tokens / context_window) at which the TUI
 * should automatically compact. Pi uses 75% by default for the same reason —
 * leaves headroom for the next turn's tool calls and assistant reply.
 */
export const DEFAULT_AUTO_COMPACT_THRESHOLD = 0.75;

export interface AutoCompactCheckOptions {
  contextWindow: number | undefined;
  latestContextTokens: number | undefined;
  threshold?: number;
}

/** Returns true when the latest context usage has crossed the threshold. */
export function shouldAutoCompact(opts: AutoCompactCheckOptions): boolean {
  const window = opts.contextWindow;
  const used = opts.latestContextTokens;
  const threshold = opts.threshold ?? DEFAULT_AUTO_COMPACT_THRESHOLD;
  if (window === undefined || used === undefined || window === 0) return false;
  return used / window >= threshold;
}

function detectPreviousSummary(
  messages: MessageRecord[],
): { previous: string; newMessages: MessageRecord[] } | undefined {
  if (messages.length === 0) return undefined;
  const first = messages[0];
  if (first === undefined) return undefined;
  if (first.role !== "user" || !first.content.startsWith(SUMMARY_MARKER)) {
    return undefined;
  }
  return {
    previous: first.content.slice(SUMMARY_MARKER.length),
    newMessages: messages.slice(1),
  };
}
