import {
  getStrataPaths,
  type JsonObject,
  type JsonValue,
  type MessageRecord,
  SessionStore,
} from "@strata/core";
import type { ModelAdapter } from "./types.js";

// Prompts ported verbatim from pi-mono (`coding-agent/src/core/compaction/{utils,compaction}.ts`).

const SUMMARIZATION_SYSTEM_PROMPT = `You are a context summarization assistant. Your task is to read a conversation between a user and an AI coding assistant, then produce a structured summary following the exact format specified.

Do NOT continue the conversation. Do NOT respond to any questions in the conversation. ONLY output the structured summary.`;

const SUMMARIZATION_PROMPT = `The messages above are a conversation to summarize. Create a structured context checkpoint summary that another LLM will use to continue the work.

Use this EXACT format:

## Goal
[What is the user trying to accomplish? Can be multiple items if the session covers different tasks.]

## Constraints & Preferences
- [Any constraints, preferences, or requirements mentioned by user]
- [Or "(none)" if none were mentioned]

## Progress
### Done
- [x] [Completed tasks/changes]

### In Progress
- [ ] [Current work]

### Blocked
- [Issues preventing progress, if any]

## Key Decisions
- **[Decision]**: [Brief rationale]

## Next Steps
1. [Ordered list of what should happen next]

## Critical Context
- [Any data, examples, or references needed to continue]
- [Or "(none)" if not applicable]

Keep each section concise. Preserve exact file paths, function names, and error messages.`;

const UPDATE_SUMMARIZATION_PROMPT = `The messages above are NEW conversation messages to incorporate into the existing summary provided in <previous-summary> tags.

Update the existing structured summary with new information. RULES:
- PRESERVE all existing information from the previous summary
- ADD new progress, decisions, and context from the new messages
- UPDATE the Progress section: move items from "In Progress" to "Done" when completed
- UPDATE "Next Steps" based on what was accomplished
- PRESERVE exact file paths, function names, and error messages
- If something is no longer relevant, you may remove it

Use this EXACT format:

## Goal
[Preserve existing goals, add new ones if the task expanded]

## Constraints & Preferences
- [Preserve existing, add new ones discovered]

## Progress
### Done
- [x] [Include previously done items AND newly completed items]

### In Progress
- [ ] [Current work - update based on progress]

### Blocked
- [Current blockers - remove if resolved]

## Key Decisions
- **[Decision]**: [Brief rationale] (preserve all previous, add new)

## Next Steps
1. [Update based on current state]

## Critical Context
- [Preserve important context, add new if needed]

Keep each section concise. Preserve exact file paths, function names, and error messages.`;

const TURN_PREFIX_SUMMARIZATION_PROMPT = `This is the PREFIX of a turn that was too large to keep. The SUFFIX (recent work) is retained.

Summarize the prefix to provide context for the retained suffix:

## Original Request
[What did the user ask for in this turn?]

## Early Progress
- [Key decisions and work done in the prefix]

## Context for Suffix
- [Information needed to understand the retained recent work]

Be concise. Focus on what's needed to understand the kept suffix.`;

const SUMMARY_MARKER = "Summary of our earlier conversation:\n\n";
const DEFAULT_KEEP_RECENT_TOKENS = 20_000;

export interface CompactSessionOptions {
  sessionId: string;
  model: ModelAdapter;
  repoRoot?: string;
  signal?: AbortSignal;
  keepRecentTokens?: number;
  reason?: "manual" | "threshold" | "overflow";
}

export interface CompactSessionResult {
  sessionId: string;
  summary: string;
  messagesSummarized: number;
  /** True if the session already had a summary and we merged new messages into it. */
  incremental: boolean;
  firstKeptMessageId: number;
  lastMessageId: number;
  tokensBefore: number;
  isSplitTurn: boolean;
  turnPrefixMessagesSummarized: number;
}

/**
 * Appends a compaction checkpoint event generated by the model. The original
 * message log remains intact; future model contexts are rebuilt as:
 *   [fresh system messages, summary checkpoint, kept recent messages, new user turn]
 *
 * If the session has an earlier compaction checkpoint, the summarizer receives
 * that previous summary plus messages from the previous kept boundary through
 * the new cut point. This mirrors Pi's repeated-compaction behavior: messages
 * that survived a prior compaction are re-summarized when the boundary moves,
 * so they are not lost from the compacted context.
 *
 * For very large single turns, the cut point may land at an assistant message.
 * In that case we summarize the turn prefix separately and merge it into the
 * main checkpoint while keeping the suffix messages verbatim.
 */
export async function compactSession(
  options: CompactSessionOptions,
): Promise<CompactSessionResult> {
  const repoRoot = getStrataPaths(options.repoRoot).repoRoot;
  const store = await SessionStore.open(repoRoot);
  try {
    const allMessages = nonSystemMessages(store, options.sessionId);
    if (allMessages.length === 0) {
      throw new Error("no messages to compact");
    }

    const latest = latestCompactionRecord(store, options.sessionId);
    const lastMessage = allMessages[allMessages.length - 1];
    if (
      latest !== undefined &&
      lastMessage !== undefined &&
      latest.lastMessageId !== undefined &&
      lastMessage.id <= latest.lastMessageId
    ) {
      throw new Error("nothing new to compact since the last compaction");
    }

    const legacy = latest === undefined ? detectLegacySummary(allMessages) : undefined;
    const previousSummary = latest?.summary ?? legacy?.previous;
    const boundaryStart = compactionBoundaryStart(allMessages, latest, legacy);
    const preparation = prepareCompaction(allMessages, boundaryStart, {
      forceAllWhenNoCut: true,
      keepRecentTokens: options.keepRecentTokens ?? DEFAULT_KEEP_RECENT_TOKENS,
    });
    if (preparation === undefined) {
      throw new Error("nothing to compact (session too small)");
    }

    const historySummary =
      preparation.messagesToSummarize.length === 0
        ? (previousSummary ?? "No prior history.")
        : await generateSummary(
            summaryOptions({
              messages: preparation.messagesToSummarize,
              model: options.model,
              previousSummary,
              signal: options.signal,
            }),
          );
    let summary = historySummary;
    if (preparation.turnPrefixMessages.length > 0) {
      const turnPrefixSummary = await generateTurnPrefixSummary(
        turnPrefixSummaryOptions({
          messages: preparation.turnPrefixMessages,
          model: options.model,
          signal: options.signal,
        }),
      );
      summary = `${historySummary}\n\n---\n\n**Turn Context (split turn):**\n\n${turnPrefixSummary}`;
    }
    summary = summary.trim();
    if (summary === "") {
      throw new Error("model returned empty summary");
    }

    const firstKeptMessage = allMessages[preparation.firstKeptMessageIndex];
    const lastMessageId = lastMessage?.id ?? firstKeptMessage?.id ?? 0;
    const firstKeptMessageId = firstKeptMessage?.id ?? lastMessageId + 1;
    const incremental = previousSummary !== undefined;
    const payload: JsonObject = {
      reason: options.reason ?? "manual",
      messagesSummarized: preparation.messagesToSummarize.length,
      turnPrefixMessagesSummarized: preparation.turnPrefixMessages.length,
      incremental,
      summary,
      firstKeptMessageId,
      lastMessageId,
      tokensBefore: preparation.tokensBefore,
      keepRecentTokens: preparation.keepRecentTokens,
      isSplitTurn: preparation.isSplitTurn,
    };
    await store.appendEvent(options.sessionId, "compaction.completed", payload);

    return {
      sessionId: options.sessionId,
      summary,
      messagesSummarized:
        preparation.messagesToSummarize.length + preparation.turnPrefixMessages.length,
      incremental,
      firstKeptMessageId,
      lastMessageId,
      tokensBefore: preparation.tokensBefore,
      isSplitTurn: preparation.isSplitTurn,
      turnPrefixMessagesSummarized: preparation.turnPrefixMessages.length,
    };
  } finally {
    store.close();
  }
}

export interface CompactionCheckpoint {
  eventId: number;
  ts: string;
  summary: string;
  firstKeptMessageId: number;
  lastMessageId?: number;
  tokensBefore?: number;
  incremental?: boolean;
  isSplitTurn?: boolean;
}

export function buildCompactedMessageRecords(
  store: SessionStore,
  sessionId: string,
): MessageRecord[] {
  const messages = nonSystemMessages(store, sessionId);
  const latest = latestCompactionRecord(store, sessionId);
  if (latest !== undefined) {
    return [
      summaryMessageRecord(sessionId, latest.summary, latest.ts),
      ...messages.filter((message) => message.id >= latest.firstKeptMessageId),
    ];
  }
  const legacy = detectLegacySummary(messages);
  if (legacy !== undefined) {
    return messages;
  }
  return messages;
}

export function latestPostCompactionAssistantContextTokens(
  store: SessionStore,
  sessionId: string,
): number | undefined {
  const messages = nonSystemMessages(store, sessionId);
  const latest = latestCompactionRecord(store, sessionId);
  const minMessageId = latest?.lastMessageId;
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message === undefined) continue;
    if (minMessageId !== undefined && message.id <= minMessageId) {
      return undefined;
    }
    if (message.role === "assistant" && message.usage !== null) {
      return message.usage.total;
    }
  }
  return undefined;
}

export function latestCompactionRecord(
  store: SessionStore,
  sessionId: string,
): CompactionCheckpoint | undefined {
  const events = store.listEvents(sessionId, "compaction.completed");
  for (let index = events.length - 1; index >= 0; index -= 1) {
    const event = events[index];
    if (event === undefined) continue;
    const payload = event.payload;
    const summary = optionalString(payload.summary);
    const firstKeptMessageId = optionalNumber(payload.firstKeptMessageId);
    if (summary === undefined || firstKeptMessageId === undefined) {
      continue;
    }
    const checkpoint: CompactionCheckpoint = {
      eventId: event.id,
      ts: event.ts,
      summary,
      firstKeptMessageId,
    };
    const lastMessageId = optionalNumber(payload.lastMessageId);
    if (lastMessageId !== undefined) checkpoint.lastMessageId = lastMessageId;
    const tokensBefore = optionalNumber(payload.tokensBefore);
    if (tokensBefore !== undefined) checkpoint.tokensBefore = tokensBefore;
    const incremental = optionalBoolean(payload.incremental);
    if (incremental !== undefined) checkpoint.incremental = incremental;
    const isSplitTurn = optionalBoolean(payload.isSplitTurn);
    if (isSplitTurn !== undefined) checkpoint.isSplitTurn = isSplitTurn;
    return checkpoint;
  }
  return undefined;
}

interface CompactionPreparation {
  firstKeptMessageIndex: number;
  messagesToSummarize: MessageRecord[];
  turnPrefixMessages: MessageRecord[];
  isSplitTurn: boolean;
  tokensBefore: number;
  keepRecentTokens: number;
}

function prepareCompaction(
  messages: MessageRecord[],
  boundaryStart: number,
  options: { keepRecentTokens: number; forceAllWhenNoCut: boolean },
): CompactionPreparation | undefined {
  const boundaryEnd = messages.length;
  if (boundaryStart >= boundaryEnd) {
    return undefined;
  }
  const tokensBefore = estimateContextTokens(messages.slice(boundaryStart)).tokens;
  const cutPoint = findCutPoint(messages, boundaryStart, boundaryEnd, options.keepRecentTokens);
  const historyEnd = cutPoint.isSplitTurn
    ? cutPoint.turnStartIndex
    : cutPoint.firstKeptMessageIndex;
  let messagesToSummarize = messages.slice(boundaryStart, historyEnd);
  let turnPrefixMessages = cutPoint.isSplitTurn
    ? messages.slice(cutPoint.turnStartIndex, cutPoint.firstKeptMessageIndex)
    : [];

  if (messagesToSummarize.length === 0 && turnPrefixMessages.length === 0) {
    if (boundaryStart === 0 || options.forceAllWhenNoCut) {
      messagesToSummarize = messages.slice(boundaryStart, boundaryEnd);
      return {
        firstKeptMessageIndex: boundaryEnd,
        messagesToSummarize,
        turnPrefixMessages,
        isSplitTurn: false,
        tokensBefore,
        keepRecentTokens: options.keepRecentTokens,
      };
    } else {
      return undefined;
    }
  }

  return {
    firstKeptMessageIndex: cutPoint.firstKeptMessageIndex,
    messagesToSummarize,
    turnPrefixMessages,
    isSplitTurn: cutPoint.isSplitTurn,
    tokensBefore,
    keepRecentTokens: options.keepRecentTokens,
  };
}

interface CutPointResult {
  firstKeptMessageIndex: number;
  turnStartIndex: number;
  isSplitTurn: boolean;
}

function findCutPoint(
  messages: MessageRecord[],
  startIndex: number,
  endIndex: number,
  keepRecentTokens: number,
): CutPointResult {
  const cutPoints = findValidCutPoints(messages, startIndex, endIndex);
  if (cutPoints.length === 0) {
    return { firstKeptMessageIndex: startIndex, turnStartIndex: -1, isSplitTurn: false };
  }

  let accumulatedTokens = 0;
  let cutIndex = cutPoints[0] ?? startIndex;
  for (let index = endIndex - 1; index >= startIndex; index -= 1) {
    accumulatedTokens += estimateMessageTokens(messages[index]);
    if (accumulatedTokens >= keepRecentTokens) {
      cutIndex = cutPoints.find((candidate) => candidate >= index) ?? cutIndex;
      break;
    }
  }

  const cutMessage = messages[cutIndex];
  const isUserMessage = cutMessage?.role === "user";
  const turnStartIndex = isUserMessage ? -1 : findTurnStartIndex(messages, cutIndex, startIndex);
  return {
    firstKeptMessageIndex: cutIndex,
    turnStartIndex,
    isSplitTurn: !isUserMessage && turnStartIndex !== -1,
  };
}

function findValidCutPoints(
  messages: MessageRecord[],
  startIndex: number,
  endIndex: number,
): number[] {
  const cutPoints: number[] = [];
  for (let index = startIndex; index < endIndex; index += 1) {
    const role = messages[index]?.role;
    if (role === "user" || role === "assistant") {
      cutPoints.push(index);
    }
  }
  return cutPoints;
}

function findTurnStartIndex(
  messages: MessageRecord[],
  entryIndex: number,
  startIndex: number,
): number {
  for (let index = entryIndex; index >= startIndex; index -= 1) {
    if (messages[index]?.role === "user") {
      return index;
    }
  }
  return -1;
}

async function generateSummary(options: {
  messages: MessageRecord[];
  model: ModelAdapter;
  previousSummary?: string;
  signal?: AbortSignal;
}): Promise<string> {
  const conversationText = serializeConversation(options.messages);
  let userPrompt: string;
  if (options.previousSummary !== undefined) {
    userPrompt =
      `<conversation>\n${conversationText}\n</conversation>\n\n` +
      `<previous-summary>\n${options.previousSummary}\n</previous-summary>\n\n` +
      UPDATE_SUMMARIZATION_PROMPT;
  } else {
    userPrompt = `<conversation>\n${conversationText}\n</conversation>\n\n${SUMMARIZATION_PROMPT}`;
  }
  return completeSummaryPrompt(options.model, userPrompt, options.signal);
}

function summaryOptions(options: {
  messages: MessageRecord[];
  model: ModelAdapter;
  previousSummary: string | undefined;
  signal: AbortSignal | undefined;
}): Parameters<typeof generateSummary>[0] {
  const result: Parameters<typeof generateSummary>[0] = {
    messages: options.messages,
    model: options.model,
  };
  if (options.previousSummary !== undefined) {
    result.previousSummary = options.previousSummary;
  }
  if (options.signal !== undefined) {
    result.signal = options.signal;
  }
  return result;
}

async function generateTurnPrefixSummary(options: {
  messages: MessageRecord[];
  model: ModelAdapter;
  signal?: AbortSignal;
}): Promise<string> {
  const userPrompt = `<conversation>\n${serializeConversation(options.messages)}\n</conversation>\n\n${TURN_PREFIX_SUMMARIZATION_PROMPT}`;
  return completeSummaryPrompt(options.model, userPrompt, options.signal);
}

function turnPrefixSummaryOptions(options: {
  messages: MessageRecord[];
  model: ModelAdapter;
  signal: AbortSignal | undefined;
}): Parameters<typeof generateTurnPrefixSummary>[0] {
  const result: Parameters<typeof generateTurnPrefixSummary>[0] = {
    messages: options.messages,
    model: options.model,
  };
  if (options.signal !== undefined) {
    result.signal = options.signal;
  }
  return result;
}

async function completeSummaryPrompt(
  model: ModelAdapter,
  userPrompt: string,
  signal: AbortSignal | undefined,
): Promise<string> {
  const request: Parameters<ModelAdapter["complete"]>[0] = {
    messages: [
      { role: "system", content: SUMMARIZATION_SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ],
    tools: [],
  };
  if (signal !== undefined) {
    request.signal = signal;
  }
  const response = await model.complete(request);
  const summary = response.content.trim();
  if (summary === "") {
    throw new Error("model returned empty summary");
  }
  return summary;
}

function serializeConversation(messages: MessageRecord[]): string {
  return messages.map((message) => `[${message.role}] ${message.content}`).join("\n\n");
}

function nonSystemMessages(store: SessionStore, sessionId: string): MessageRecord[] {
  return store.listMessages(sessionId).filter((message) => message.role !== "system");
}

function compactionBoundaryStart(
  messages: MessageRecord[],
  latest: CompactionCheckpoint | undefined,
  legacy: { previous: string; newMessages: MessageRecord[] } | undefined,
): number {
  if (latest !== undefined) {
    const index = messages.findIndex((message) => message.id === latest.firstKeptMessageId);
    if (index >= 0) return index;
    const after = messages.findIndex((message) => message.id > latest.firstKeptMessageId);
    return after >= 0 ? after : messages.length;
  }
  if (legacy !== undefined) {
    return Math.max(0, messages.length - legacy.newMessages.length);
  }
  return 0;
}

function summaryMessageRecord(sessionId: string, summary: string, ts: string): MessageRecord {
  return {
    id: 0,
    sessionId,
    role: "user",
    content: `${SUMMARY_MARKER}${summary}`,
    toolCallId: null,
    toolCalls: null,
    attachments: null,
    usage: null,
    ts,
  };
}

function detectLegacySummary(
  messages: MessageRecord[],
): { previous: string; newMessages: MessageRecord[] } | undefined {
  if (messages.length === 0) return undefined;
  const first = messages[0];
  if (first === undefined) return undefined;
  if (first.role !== "user" || !first.content.startsWith(SUMMARY_MARKER)) {
    return undefined;
  }
  return {
    previous: first.content.slice(SUMMARY_MARKER.length),
    newMessages: messages.slice(1),
  };
}

interface ContextUsageEstimate {
  tokens: number;
}

function estimateContextTokens(messages: MessageRecord[]): ContextUsageEstimate {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message?.role === "assistant" && message.usage !== null) {
      let trailingTokens = 0;
      for (let trailing = index + 1; trailing < messages.length; trailing += 1) {
        trailingTokens += estimateMessageTokens(messages[trailing]);
      }
      return { tokens: message.usage.total + trailingTokens };
    }
  }
  return { tokens: messages.reduce((sum, message) => sum + estimateMessageTokens(message), 0) };
}

function estimateMessageTokens(message: MessageRecord | undefined): number {
  if (message === undefined) return 0;
  let chars = message.content.length;
  if (message.toolCalls !== null) {
    chars += JSON.stringify(message.toolCalls).length;
  }
  if (message.attachments !== null) {
    chars += estimateAttachmentChars(message.attachments);
  }
  return Math.ceil(chars / 4);
}

function estimateAttachmentChars(value: JsonValue): number {
  if (Array.isArray(value)) {
    return value.length * 4800;
  }
  return 4800;
}

function optionalString(value: JsonValue | undefined): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function optionalNumber(value: JsonValue | undefined): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function optionalBoolean(value: JsonValue | undefined): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

/**
 * Default context-window reserve used for threshold auto-compaction. Pi uses
 * `contextWindow - reserveTokens` rather than a fixed percentage so larger
 * windows are not compacted unnecessarily early.
 */
export const DEFAULT_AUTO_COMPACT_RESERVE_TOKENS = 16_384;

export interface AutoCompactCheckOptions {
  contextWindow: number | undefined;
  latestContextTokens: number | undefined;
  reserveTokens?: number;
  /**
   * Legacy override retained for focused tests and callers that deliberately
   * want ratio-based behavior. Omit this for Pi-style reserve-token checks.
   */
  threshold?: number;
}

/** Returns true when the latest context usage has crossed the threshold. */
export function shouldAutoCompact(opts: AutoCompactCheckOptions): boolean {
  const window = opts.contextWindow;
  const used = opts.latestContextTokens;
  if (window === undefined || used === undefined || window <= 0) return false;
  if (opts.threshold !== undefined) {
    return used / window >= opts.threshold;
  }
  const reserveTokens = opts.reserveTokens ?? DEFAULT_AUTO_COMPACT_RESERVE_TOKENS;
  return used > window - reserveTokens;
}
